# Machine Learning Engineering Zoom Camp 2022
Lecture 1: [link](https://www.youtube.com/watch?v=MqI8vt3-cag&list=PL3MmuxUbc_hIhxl5Ji8t4O6lPAOpHaCLR&index=1)

Homework assignment : [link](https://github.com/alexeygrigorev/mlbookcamp-code/tree/master/course-zoomcamp/cohorts/2022/01-intro)

## Lecture notes
### Numpy
[Extended numpy Notebook](https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/appendix-c-numpy.ipynb)

[Numpy Cheat sheet](https://res.cloudinary.com/dyd911kmh/image/upload/f_auto,q_auto:best/v1634603461/Screen_Shot_2021-10-18_at_8.27.05_PM_nweo4x.png)


In [1]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.full(5, 2)

array([2, 2, 2, 2, 2])

In [9]:
np.array([5, 7.8, 3, 0.3, 8, 10])

array([ 5. ,  7.8,  3. ,  0.3,  8. , 10. ])

In [10]:
a = np.array([5, 7.8, 3, 0.3, 8, 10])
a[2]

3.0

In [12]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [15]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
n = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
n[2, 1]

8

In [22]:
n[2, 1] = 80
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 80,  9]])

In [23]:
n[1]

array([4, 5, 6])

In [25]:
n[:, 1]

array([ 2,  5, 80])

In [26]:
n[:, 1] = [0, 0, 0]
n

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [32]:
np.random.seed(10)
np.random.rand(5, 3) # uniform distr

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096]])

In [34]:
np.random.randn(5, 3) # normal distr

array([[ 1.49057364,  0.75636693,  0.46964093],
       [-0.23396259,  0.35365794,  1.78370094],
       [-0.35030121, -0.9896496 , -0.63425417],
       [ 1.89876222,  1.99652279, -1.11867153],
       [ 2.18032831,  0.19046688,  1.2616859 ]])

In [35]:
np.random.randint(low = 0, high = 100, size = (5, 3))

array([[11, 28, 74],
       [88,  9, 15],
       [18, 80, 71],
       [88, 11, 17],
       [46,  7, 75]])

In [37]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [38]:
a + 1

array([1, 2, 3, 4, 5])

In [44]:
b = 10 + (a * 2)**2 / 100
b

array([10.  , 10.04, 10.16, 10.36, 10.64])

In [51]:
b = ( a + b ) / 10
b

array([1.   , 1.104, 1.216, 1.336, 1.464])

In [52]:
a > 2

array([False, False, False,  True,  True])

In [57]:
a > b

array([False, False,  True,  True,  True])

In [58]:
a[ a > b ]

array([2, 3, 4])

In [60]:
a.min(), a.max()

(0, 4)

In [61]:
a.mean(), a.std()

(2.0, 1.4142135623730951)

In [69]:
U = np.array(([1,2,3,4], [4,5,6,7], [8,9,10,11]))
v = np.array([1,1,1,1])
U, v

(array([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([1, 1, 1, 1]))

In [88]:
# matrix vector multiplication

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        row_result = 0
        for j in range(len(v)):
            row_result = row_result + U[i,j] * v[j]
        result[i] = row_result
    return result
        
matrix_vector_multiplication(U, v)
    

array([10., 22., 38.])

In [89]:
U.dot(v)

array([10, 22, 38])

In [90]:
V = np.array(([1,2,3,4,5], [4,5,6,7,8], [8,9,10,11,12], [8,9,10,11,12]))
V

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 8,  9, 10, 11, 12],
       [ 8,  9, 10, 11, 12]])

In [96]:
# matrix matrix multiplication

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    result = np.zeros((U.shape[0], V.shape[1]))

    for i in range(V.shape[1]):
        result[:, i] = matrix_vector_multiplication(U, V[:, i])
    return result

matrix_matrix_multiplication(U, V)

array([[ 65.,  75.,  85.,  95., 105.],
       [128., 150., 172., 194., 216.],
       [212., 250., 288., 326., 364.]])

In [97]:
U.dot(V)

array([[ 65,  75,  85,  95, 105],
       [128, 150, 172, 194, 216],
       [212, 250, 288, 326, 364]])

In [103]:
# identity matrix

I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [122]:
U.dot(I)

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [131]:
# Inverse matrix

Vs = np.array(([1,1,2], [0,0.5,1], [0,2,1]))
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [132]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [133]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Pandas

[Extended pandas Notebook](https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/appendix-d-pandas.ipynb)

[Pandas Cheat sheet](https://res.cloudinary.com/dyd911kmh/image/upload/f_auto,q_auto:best/v1621255989/Pandas_Cheat_Sheet_for_Data_Science_in_Python_hqirhp.png)

In [134]:
import pandas as pd

In [135]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [136]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [137]:
# Alternatively, we can use a list of dictionaries to create a dataframe:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [139]:
df = pd.DataFrame(data)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [140]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [142]:
df.iloc[[1,4]]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
4        Pickup  32340

In [145]:
df.reset_index(drop = True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [148]:
df[df['Year'] >= 2015]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450  
4        Pickup  32340

In [151]:
df['Vehicle_Style'].str.replace(' ', '_').str.lower()

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [152]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [154]:
df.describe()

Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [156]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [158]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [160]:
df.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

In [161]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [164]:
df.to_dict('records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]

## Homework

[Homework assignment](https://github.com/alexeygrigorev/mlbookcamp-code/tree/master/course-zoomcamp/cohorts/2022/01-intro)

[Dataset for homework assignment](https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv)

### Question 1

What's the version of NumPy & Pandas that you installed?

In [168]:
np.__version__, pd.__version__

('1.21.5', '1.4.3')

### Question 2

How many records are in the dataset?

Here you need to specify the number of rows.

- 16
- 6572
- **11914**
- 18990

In [169]:
data = pd.read_csv("data.csv")
data.shape

(11914, 16)

### Question 3
Who are the most frequent car manufacturers (top-3) according to the dataset?

- Chevrolet, Volkswagen, Toyota
- Chevrolet, Ford, Toyota
- Ford, Volkswagen, Toyota
- **Chevrolet, Ford, Volkswagen**

Note: You should rely on "Make" column in this question.

In [177]:
data.head(3)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350

In [179]:
data.Make.value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

### Question 4

What's the number of unique Audi car models in the dataset?

- 3
- 16
- 26
- **34**

In [180]:
data[data.Make == 'Audi'].Model.nunique()

34

### Question 5
How many columns in the dataset have missing values?

- **5**
- 6
- 7
- 8

In [186]:
data.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

### Question 6
1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Now, calculate the median value of "Engine Cylinders" once again.
Has it changed?

Hint: refer to existing mode and median functions to complete the task.

- Yes
- **No**

In [188]:
np.median(data[data['Engine Cylinders'].notna()]['Engine Cylinders'])

6.0

In [202]:
data['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [197]:
data['Engine Cylinders'].fillna(4.0)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [198]:
np.median(data['Engine Cylinders'].fillna(4.0))

6.0

### Question 7
1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the value of the first element of w?

Note: You just implemented linear regression. We'll talk about it in the next lesson.

- -0.0723
- **4.5949**
- 31.6537
- 63.5643

In [211]:
X = data.loc[data.Make == 'Lotus', ['Engine HP', 'Engine Cylinders']].drop_duplicates().values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [244]:
XTX = (X.T).dot(X)
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [245]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

XTX_inv.dot(X.T).dot(y)

array([  4.59494481, -63.56432501])